package ejercicio1;

import static org.junit.Assert.*;

import org.junit.Test;

public class CuentaTest {
	
	private String nombre;
	private String cuenta;
	private double saldo;
	private double tipoIn;

	public CuentaTest (String nom, String cue, double sal, double tipo)
    {
        nombre =nom;
        cuenta=cue;
        saldo=sal;
        tipoIn=tipo;
    }
	
	@Test
	public void testIngresar() {
		Cuenta c = new Cuenta("Pablo","123456",100,3);
		try {
			c.ingresar(-1000);
			fail("Fallo, debería haber lanzado la excepción");
		} catch (Exception e) {
			//PRUEBA saisfactoria;
		}
	}

}
